### ISSUE TITLE
UK country flags

### ISSUE THREAD

**Issue by mrlooovermaaan** [fraz3alpha/running-challenges#100]
How about badges for Scotland, Wales, England and Northern Ireland (if you can decide what that should be!).  Could also add Jersey, Guernsey and IoM I guess since these are not technically part of any of the above.

**Comment by fraz3alpha** [comment]
We are sticking with the flags representing the top level countries that parkrun operates under, we aren't going to subdivide them any more.
The one change we expect at some point is Namibia and Swaziland to move from under South Africa, but we keep the flags for the UK the same unless parkrun HQ move the regions to a top level

**Comment by mrlooovermaaan** [comment]
No worries, cheers.
