### ISSUE TITLE
Plugin does not load: Error: [object Object]

### ISSUE THREAD

**Issue by sebiush** [fraz3alpha/running-challenges#103]
Getting the Error: [object Object] 

![2018-09-19 07_58_57-rezultaty _ parkrun polska](https://user-images.githubusercontent.com/23718884/45733689-f3602400-bbe1-11e8-9e0a-2026a65fb5c9.png)

Using Chrome 69.0.3497.92

**Comment by fraz3alpha** [comment]
Hi, I'm sorry you are getting an error @sebiush . If you open the Javascript console (View > Developer > Javascript Console), are there any more useful errors listed there?

**Comment by sebiush** [comment]
Hi @fraz3alpha 
Thank you for taking a look on this one. Here's what I'm getting:

`Progress: Loading <a href="https://running-challenges.co.uk" target="_blank">Running Challenges</a> Badges
i18n.js:377 I18N:table_all_results:Wszystkie wyniki
content-script-athleteeventresultshistory.js:146 Progress: Parsing Results
i18n.js:377 I18N:table_all_results:Wszystkie wyniki
content-script-athleteeventresultshistory.js:146 Progress: Parsed Results
content-script-athleteeventresultshistory.js:146 Progress: Loading saved data
content-script-athleteeventresultshistory.js:146 Progress: Loaded saved data
content-script-athleteeventresultshistory.js:146 Progress: Loading geo data
content-script-athleteeventresultshistory.js:521 {message: "Could not establish connection. Receiving end does not exist."}
content-script-athleteeventresultshistory.js:522 An error occurred: [object Object]
browser.storage.sync.get.then.then.then.catch.error @ content-script-athleteeventresultshistory.js:522
Promise.catch (async)
(anonymous) @ content-script-athleteeventresultshistory.js:520
content-script-athleteeventresultshistory.js:146 Progress: Error: [object Object]
web_widget.c4493a639da077eb0ee4.js:8 Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices​
`
![image](https://user-images.githubusercontent.com/23718884/46214049-7861e080-c33a-11e8-8cf2-fdfddaf6a8b5.png)

**Comment by sebiush** [comment]
Just updated to the latest Chrome build (69.0.3497.100) and no issues here. Feel free to close this one.

**Comment by fraz3alpha** [comment]
I'm glad you got it working! I suspect something failed to load the first time and it was accidentally saved in the internal cache - and updating cleared it all to start again. If anyone else has this problem, perhaps they could either try uninstalling, or disabling the plugin before reinstalling / re-enabling it to see if it helps
