### ISSUE TITLE
Add textual description to explain each of the challenges

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#11]
Add as either hover help (on a ? icon maybe) or a link to click and expand.

Text description for each:

Tourist - Run at 20+ different parkrun locations anywhere in the world.
Cowell Club - Run at 100+ different parkrun locations anywhere in the world. Named after the first parkrunners to complete it.
Alphabeteer - Run at a parkrun locations starting with each letter of the English alphabet (except X).
Single-Ton - Run 100+ parkruns at the same location.
Double-Ton - Run 200+ parkruns at the same location.
Stopwatch Bingo - Collect all the seconds from 00 to 59 in your finishing times.
Pirates! - Run seven Cs and an R (say it out loud).
Stayin' Alive - Run three Bees and three Gees.
Compass Club - Run at a parkrun named after each of the four compass points.
The Full Ponty - Run at all the parkruns named ponty... or ponte...
Bushy Pilgrimage - Run at Bushy parkrun, where it all began.
NYD Double - Run two parkruns on one New Year's Day.
Groundhog Day - Finish with the same time at the same parkrun location on two consecutive parkrun weeks.
Regionnaire - Run all the parkrun locations in a geographical region.
Bronze Level Obsessive - Run 30+ parkruns in one calendar year.
Silver Level Obsessive - Run 40+ parkruns in one calendar year.
Gold Level Obsessive - Run 50+ parkruns in one calendar year.

Volunteer main heading (to be added) - Get a purple badge when you've done a role once, get a star for doing the role 5+ times, two stars for 10+ times, three stars for 25+ times.

**Comment by fraz3alpha** [comment]
All done!
