### ISSUE TITLE
Exclude prison events from Regionnaire challenge

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#12]
Prison parkrun events are not publicly accessible and so can't be achieved by most parkrunners in trying to complete the region that includes the prison parkrun.

Probably have to do this based on a manual list because `geo.xml` doesn't identify prison parkruns. The only difference is that website homepage for the parkrun says it's not accessible to the public but that doesn't really help.

**Comment by fraz3alpha** [comment]
As if by magic they have disappeared!
