### ISSUE TITLE
Link to Google Maps for Average parkrun lat/lon location

### ISSUE THREAD

**Issue by rleeden** [fraz3alpha/running-challenges#120]
I think it would be a nice tweak to link to Google maps from the Average parkrun lat/lon location to have an easy way to visualise where your 'Average parkrun' is based.
So in my case my average parkrun location is currently: 51.50495, -0.46637, which would require a link to Google Maps as follows: [https://www.google.co.uk/maps/search/51.50495,-0.46637/@51.50495,-0.46637,10z](https://www.google.co.uk/maps/search/51.50495,-0.46637/@51.50495,-0.46637,10z)
The last element of the URL  (**10z**) can be adjusted to change the zoom level.

**Comment by fraz3alpha** [comment]
Yep, pretty sure we can add that in no problem!

**Comment by fraz3alpha** [comment]
This will be in the next version, v0.7.3
