### ISSUE TITLE
Add a note/image/tshirt next to when your milestone runs were (or a table with them in)

### ISSUE THREAD

**Issue by marcburrows** [fraz3alpha/running-challenges#129]
Its difficult to find our milestone runs in the athlete page, it would be great to either have the milestone t-shirt put next to the specific run or have a new table that shows when and where the milestone runs were.

**Comment by fraz3alpha** [comment]
We don't actually touch either the milestone tees at the top, or the results table at the bottom - they are all stock on the parkrun page.  I have been thinking about how to track progress though, maybe we could alter the table at the bottom with an extra column to add those kinds of things in - I like the idea

**Comment by markbeech** [comment]
If you are adding a milestone table, could you also add an estimated date for the next mile stone?

My own table on https://markrun.org/rfc/milestones/ makes some assumptions that there is only 1 parkrun each week and that I won't miss it, which is accurate enough for my needs. It might be possible to get a more accurate guess by taking into account each athletes current rate of progress.

**Comment by marcburrows** [comment]
Cheers @fraz3alpha! I might take a look at the code and see if I can look into it myself and raise a PR.
