### ISSUE TITLE
NYD Groundhog Challenge 

### ISSUE THREAD

**Issue by JazzyJ87** [fraz3alpha/running-challenges#137]
As per https://m.facebook.com/groups/1733916136845554?view=permalink&id=2316036805300148

**Comment by JazzyJ87** [comment]
As other countries have the possibility of doubles in days that aren't NYD - should think of a suitable rename for the challenge. Seeing Double? Double Day Double Time?

**Comment by JazzyJ87** [comment]
Test case: http://www.parkrun.org.uk/results/athleteresultshistory/?athleteNumber=280273

**Comment by JazzyJ87** [comment]
Danish double case: http://www.parkrun.org.uk/results/athleteresultshistory/?athleteNumber=19147

**Comment by itsafrogslife** [comment]
> As other countries have the possibility of doubles in days that aren't NYD - should think of a suitable rename for the challenge. Seeing Double? Double Day Double Time?

I quite like Golden Groundhog :-)
