### ISSUE TITLE
Add badges for each country's special event day

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#144]
The current list of special event days are:
- Thanksgiving
- Canada Day (although we haven't seen one of these yet)
- Christmas Eve
- Christmas Day
- Boxing Day
- Orthodox Christmas
- Chinese New Year

- New Years Day

New Year's Day is covered by the double badge, and Christmas is covered by a Christmas badge - however I think we should extend the Christmas badge to include running on Christmas Eve/Boxing day in one of the appropriate countries, or Orthodox Christmas in Russia. That leaves Thanksgiving, Chinese New Year, and Canada Day, but I've one seen Thanksgiving runs happen so far - so that should get it's own badge.

- [ ] Extend the Christmas Day badge to include 24th/26th December or Orthodox Christmas for those qualifying countries
- [ ] Add Thanksgiving Turkey badge

- [ ] See if there have actually been any Canada Day/Chinese New Year events and if that is work putting a badge in for

**Comment by JazzyJ87** [comment]
Happy to give the Turkey badge a go. I'm thinking of updating the challenge_on_dates somehow to incorporate not fixed holidays e.g. Fourth Thursday of November (Thanksgiving) style.

Would be easier for Thanksgiving to test for all dates 22 to 28 in November, so sending an array of options for the date match. Probably using getDay() to make sure it's a Thursday. Doesn't create a fully flexible function for non-fixed holidays.

A quick search finds a module for the Chinese Calendar: https://www.npmjs.com/package/date-chinese

**Comment by JazzyJ87** [comment]
For Thanksgiving, would we also need to test for Country?

**Comment by fraz3alpha** [comment]
I think for the purpose of Thanksgiving and Chinese New Year, and in the spirit of keeping it simple, we could just hardcode the dates for a block of time, e.g. from the founding of parkrun to 2025 or something, and then include them in a javascript file - they can be updated as necessary in the future. We could use a library, but I think it would be more simple this way. If people are still using this extension in 6 years, we'll add a few more dates for very little effort :)

If you want to give it a go I'm happy for you to do so, I've only just got back home after the Christmas break and haven't thought about this that much, but created this as a follow up to an email we received

**Comment by JazzyJ87** [comment]
I've added a Pull Request for the Thanksgiving Turkey badge in #146

**Comment by JazzyJ87** [comment]
No evidence of a Canada Day pr that wasn't on a Saturday anyway

**Comment by PureAbstract** [comment]
> No evidence of a Canada Day pr that wasn't on a Saturday anyway
FYI, a friend of mine did Meadowvale last Monday - 
https://www.parkrun.ca/meadowvale/results/weeklyresults/?runSeqNumber=64
