### ISSUE TITLE
Switch to pulling geodata from running-challenges.co.uk

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#145]
As it stands the extension loads two static files from the parkrun website - the geo.xml file (containing the 5k parkrun locations and country/region information), and the event technical information wiki page which tells us whether an event has started yet. If we want to add in the junior parkrun events, this is another page, and it is already getting a bit busy here. In order to load things more reliably, and to not put extra strain on the parkrun website, we can proxy these files on our static site, and do the relevant parsing in advance.

For example:
- Fetch:
  - Fetch 5k parkrun location info
  - Fetch 2k parkrun location info
  - Fetch event info
- Parse the data into one list of events, and combine with the live/pending event data. We can also make the property types right from the start, e.g. lat/lon data as floats, something the XML can't encode natively.

We have had a few bugs reported when the wiki isn't working well (presumably during busy times), and it stops people getting going with the extension - therefore it would be useful to take any extra load off it. It also means if the data moves, we can update our code centrally without every user having to update their extension.

**Comment by fraz3alpha** [comment]
We had two emails from users this morning who were unable to save their home parkrun on the options page because it couldn't fetch the data - I think it was likely the technical event information that was the problem, as I saw that error on my own page, but it could have been the geo data too.

**Comment by rboyatt** [comment]
I've also seen a couple of failures today - failing to load the technical event info page seemed to be the source of the problem.

**Comment by fraz3alpha** [comment]
I'm going to close this, and keep it simple with how it is now. It'll sometimes fail I guess, but it's a lot of overhead maintaining something else
