### ISSUE TITLE
Allow `Ż` to be included as a `Z` in the parkrun alphabet.

### ISSUE THREAD

**Issue by marcburrows** [fraz3alpha/running-challenges#166]
Parkrun have changed the spelling of `Żary` parkrun to include the overdot, where it was previously just `Zary`. Numerous people have now lost the Z from their alphabet challenge. This issue has been raised to allow Ż to be included in Z, if those in charge of this app see it as the correct move to make.

**Comment by fraz3alpha** [comment]
Hi Marc, someone let us know about this via email last night, and that was the first we were aware of it.

 Ż replacing Z isn't the only change though, there are other initial letters of events in several languages which are now written correctly. 

We need to think what the right thing to do is. it was easy before as they were all effectively written in English, but now they are written correctly in their local language.  Ż might look like a Z, but it isn't a Z. I guess it's like O not being the same as Q for us.

Do we have multiple alphabet challenges? Do we coerce them all into what we see as English speakers? Do we have one massive challenge? I'm not sure there is a solution that will please everyone, so I guess we'll end up just picking one or more of them when we've got time to take a look properly!

**Comment by jgossit** [comment]
I don't like it being counted as a Z when it isn't, even though it might look/sound like a Z. I think the original being an English alphabet challenge is the way to go. Separate challenges per language could be added, although imagine they'd be missing quite a lot of letters so maybe common sense there is to exclude those until an event comes along with the letter.

**Comment by magselin** [comment]
Yes, but it would be nice if it wasn't applied retrospectively for those people like myself who have already done Zary when it was acknowledged as a Z.😏

**Comment by marcburrows** [comment]
@fraz3alpha - I thought I’d raise it as an issue, as there was a big comment thread about it. Personally, I am fine with whichever decision is made as I don’t have a Z anyway. Whatever happens, you can’t really win 😄. I think I agree with both @jgossit - a separate challenge, as this would still take people to Żary - and @magselin - keep it for those who had done it in the assumption it was a Z (Although I assume this would add unescessary complexity)

**Comment by JazzyJ87** [comment]
If several different challenges then #141 might be useful to implement to hide the non-relevant ones.
