### ISSUE TITLE
Average Parkrun Location

### ISSUE THREAD

**Issue by johnconlin** [fraz3alpha/running-challenges#173]
We have the Average parkrun lat/lon location, would i be possible to say which is the nearest parkrun to those coordinates? And If you've done it?

I appreciate it would be a moving target!

**Comment by sargant** [comment]
I've opened a PR for this enhancement in #223

**Comment by sargant** [comment]
I've opened a PR for this in #224

**Comment by fraz3alpha** [comment]
Thanks @sargant , we'll take a look. I know @lauracowen has also got an implementation for this that she did over Christmas - at least some of it is in a [branch](https://github.com/fraz3alpha/running-challenges/tree/avg-parkrun) but it doesn't look like there is a PR.

**Comment by lauracowen** [comment]
Done in V1.0.0
