### ISSUE TITLE
Polish volunteer role names have been changed

### ISSUE THREAD

**Issue by sebiush** [fraz3alpha/running-challenges#178]
Could you please grant me an access to create a PR with this translation update?

**Comment by sebiush** [comment]
Current list of roles in PL:

            "Przechowanie sprzętu": "Equipment Storage and Delivery",
            "Komunikacja i promocja": "Communications Person",
            "Koordynator woluntariuszy": "Volunteer Co-ordinator",
            "Ustawienie elementów trasy": "Pre-event Setup",
            "Instruktor nowych uczestników": "First Timers Briefing",
            "Tłumacz języka migowego": "Sign Language Support",
            "Ubezpieczanie trasy": "Marshal",
            "Zamykanie stawki": "Tail Walker",
            "Koordynator spotkania": "Run Director",
            "Rower bezpieczeństwa": "Lead Bike",
            "Wyznaczanie tempa": "Pacer (5k only)",
            "Przewodnik dla słabowidzących": "VI Guide",
            "Fotograf": "Photographer",
            "Pomiar czasu": "Timekeeper",
            "Zapasowy pomiar czasu": "Backup Timer",
            "Koordynator tunelu mety": "Funnel Manager",
            "Wręczanie tokenów na mecie": "Finish Tokens",
            "Pomoc przy wręczaniu tokens": "Finish Token Support",
             // currently parkrun system has a typo in the FTS role translation,
             // it will be most probably changed to the one below:
            "Pomoc przy wręczaniu tokenów": "Finish Token Support",
            "Skanowanie uczestników": "Barcode Scanning",
            "Sprawdzanie pozycje na mecie": "Number Checker",
            "Zbieranie elementów z trasy": "Post-event Close Down",
            "Wprowadzanie wyników": "Results Processor",
            "Sortowanie tokenów": "Token Sorting",
            "Przygotowanie raportu z biegu": "Run Report Writer",
            "Inne": "Other",
            "Prowadzący rozgrzewkę": "Warm Up Leader (junior events only)",
            "Koordynator parkingu": "Car Park Marshal",
            "Sprawdzenie trasy przed spotkaniem": "Event Day Course Check"

**Comment by sebiush** [comment]
Updated list of roles:
        
        "Przechowanie sprzętu": "Equipment Storage and Delivery",
        "Komunikacja i promocja": "Communications Person",
        "Koordynator woluntariuszy": "Volunteer Co-ordinator",
        "Ustawienie elementów trasy": "Pre-event Setup",
        "Instruktor nowych uczestników": "First Timers Briefing",
        "Tłumacz języka migowego": "Sign Language Support",
        "Ubezpieczanie trasy": "Marshal",
        "Zamykanie stawki": "Tail Walker",
        "Koordynator spotkania": "Run Director",
        "Rower bezpieczeństwa": "Lead Bike",
        "Wyznaczanie tempa": "Pacer (5k only)",
        "Przewodnik dla słabowidzących": "VI Guide",
        "Fotograf": "Photographer",
        "Pomiar czasu": "Timekeeper",
        "Zapasowy pomiar czasu": "Backup Timer",
        "Koordynator tunelu mety": "Funnel Manager",
        "Wręczanie tokenów na mecie": "Finish Tokens",
        "Pomoc przy wręczaniu tokenów": "Finish Token Support",
        "Skanowanie uczestników": "Barcode Scanning",
        "Sprawdzanie pozycji na mecie": "Number Checker",
        "Zbieranie elementów z trasy": "Post-event Close Down",
        "Wprowadzanie wyników": "Results Processor",
        "Sortowanie tokenów": "Token Sorting",
        "Przygotowanie raportu z biegu": "Run Report Writer",
        "Inne": "Other",
        "Prowadzący rozgrzewkę": "Warm Up Leader (junior events only)",
        "Koordynator parkingu": "Car Park Marshal",
        "Sprawdzenie trasy przed spotkaniem": "Event Day Course Check"

**Comment by lauracowen** [comment]
@sebiush You can fork the repository then create a PR from there, which we can then review/test/merge.

Alternatively, I can just copy/paste your changes into the file directly (but it wouldn't show as your change in GitHub then). Let me know which you prefer. Thx

**Comment by lauracowen** [comment]
Done and released.
