### ISSUE TITLE
Vinyl disc challenges

### ISSUE THREAD

**Issue by maxelkat** [fraz3alpha/running-challenges#179]
Hi Andy and Laura, apologies if you've already seen this on email, but I think it's quite a good idea and shouldn't be too bad to implement.
Briefly, it's a area-based parkrun completion challenge, where badges would be earned for completing every parkrun within a 33.3km, 45km or 78km radius of the parkrunner's specified home run (those numbers being a reference to the rotational speeds of vinyl records). Unlike the existing regionnaire badges, this would not require lists of parkruns to be maintained, but could use the already existing NENDY distance for reference.
I don't have any programming ability but I'd be happy to do the artwork if you like.
All the best, Elliott Line A1142363

**Comment by itsafrogslife** [comment]
I see we've already got the artwork!

**Comment by fraz3alpha** [comment]
Done!
