### ISSUE TITLE
Most northerly, westerly etc.. in the UK

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#2]
Like 'To the ends of the earth', but for the UK market

As suggested by James WHITE 2018-03-11

**Comment by DerekBlount** [comment]
And a world equivilent?

**Comment by lauracowen** [comment]
Or most northerly, westerly, etc for each country (top-level region)?

**Comment by DerekBlount** [comment]
Country or region would be fine. Most westerly in Southern Africa would 
be in Namibia for South Africans, One hell of a trip.

**Comment by lauracowen** [comment]
The ozzies have a compass challenge too: the most northerly, southerly, easterly, & westerly parkrun in Australia
