### ISSUE TITLE
No lists of parkruns in each region/country

### ISSUE THREAD

**Issue by josh-justjosh** [fraz3alpha/running-challenges#201]
In the latest update, when you click on the country name in the Regionnaire Explorer, you no longer get the list of parkruns in that region/country.

**Comment by fraz3alpha** [comment]
Correct. See https://running-challenges.co.uk/2019/11/19/where-did-my-flags-go.html

**Comment by fraz3alpha** [comment]
If it were to list them, it would list 600+ for the UK, which is a terrible user experience. So for now, it's not available.

**Comment by josh-justjosh** [comment]
I thought as much
