### ISSUE TITLE
Star Wars Challenge

### ISSUE THREAD

**Issue by SMFinch-perth** [fraz3alpha/running-challenges#204]
Suggestion for a challenge based on Star Wars - R2D2 and C3PO
run 2 events starting with R, 2 starting with D, 3 starting with C, one starting with a P and one starting with an O.

**Comment by josh-justjosh** [comment]
I feel as though there should also be 8 Bs (maybe 16) as well as 2 Ks, an S and another O.
That may make it impossible though!
