### ISSUE TITLE
Summary table counts tokens and tokens support separately

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#206]
In the first bit of summary, I've done 15 distinct roles but only 14 are shown on the page in the list.

Finish Tokens and Finish Tokens Support are separate in the summary table (as parkrun does) but we combined them for the badges.

Test with: 1197634

**Comment by lauracowen** [comment]
Conclusions: We should leave the Summary Table (where it currently says "15" in example above) as it is because the Finish Tokens and Finish Tokens Support roles are not necessarily so interchangeable/closely associated at all parkruns as they are at Winchester (say). What should actually be done to fix the extension's inconsistency is to create a new badge for Finish Tokens Support. Not sure what that badge should show though so I'll leave this issue open but won't fix it just yet.

**Comment by IreShane** [comment]
At Saltaire juniors we have removed the need to have Finish Token support by using knitting stitch holdersto carry the tokens instead of string. 
https://www.woolstack.co.uk/knitpro-aluminium-stitch-holders/
Personally I like the way Token and token support are combined for the challenge.
