### ISSUE TITLE
Leaprunday

### ISSUE THREAD

**Issue by jameswwright** [fraz3alpha/running-challenges#222]
Prompted by an idea from Nina Haikonen in the parkrun World Tourists Facebook group, could we have a badge to celebrate those who take part on Feb 29th aka _**leaprunday**_, as this is the first time that parkrunday falls then? Thanks!

**Comment by lauracowen** [comment]
parkrunning on leap day will be very cool for those who do it (and we're planning to!) but it doesn't make sense as a challenge. The badges represent challenges for people to attempt, not souvenirs. 

Have a good Leap Day parkrun!
