### ISSUE TITLE
Carbon footprint of tourism

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#229]
Display (in stats table after cumulative number of km travelled to parkrun) the kg of carbon emitted by that tourism.

Obviously, this would be *very* approximate (but then the cumulative km is also approximate as it's between consecutive parkruns, not there and home each week). To  keep it simple, as most people probably tourist by road, I think just calculate based on land travel (ie not get into air travel) by road. Ultimately, the absolute value would not be precise but relative comparisons could give a sense of impact, especially when travelling longer distances vs shorter distances.

DEFRA provides some emissions data and instructions that we might be able to use.

**Comment by ajhepple** [comment]
Interesting, I wonder how such a statistic will motivate tourists. I wouldn't want to discourage parkrun tourism but it is really important that this information is made available.

Perhaps, in addition to the carbon footprint of parkrun tourism by car, values for tourism by public transport and bicycle could be calculated? This would illustrate the difference between each form of transport and therefore support parkrun UK in encouraging the use of public transport to attend parkruns.
