### ISSUE TITLE
NYDD event not included in Groundhog Day

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#232]
See DMs for athlete number.

 Hi guys, I guess this comes down to how parkrun orders the results, but is there any way to order the NYDD events by time? A friend did Groundhog day but the pr results page has NYD events in the wrong order so the extension can't tell it was consecutive!

![image](https://user-images.githubusercontent.com/3322532/72716937-00d94580-3b6b-11ea-8ece-a9b3293c49bd.png)

**Comment by fraz3alpha** [comment]
That's certainly an interesting one - I don't think it's actually possible to tell what time a parkrun happened to know which order the NYD ones were done as it isn't historically recorded anywhere.
We might just have to chalk this up to "we're keeping it as simple as we can, this can't be fixed".
