### ISSUE TITLE
Average parkrun event doesn't handle when no average location is returned

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#235]
It just defaults to Bushy Park (first in the events list, I think).

Test: 5930968 (junior only: should say None because #236 ), 2363530 (both junior and 5k: should say Winchester because #236 )

**Comment by josh-justjosh** [comment]
I also notice in that person's results, there are no stats for average parkrun location or countries visited despite them having done 7 junior parkruns

**Comment by fraz3alpha** [comment]
@josh-justjosh , I've explained the junior parkrun situation in your issue #236
