### ISSUE TITLE
Combine Single-Ton and Double-Ton Challenge.

### ISSUE THREAD

**Issue by markbeech** [fraz3alpha/running-challenges#237]
Given that the single-ton is a sub-set of the double-ton challenge, would it be possible to combine them.

This would reduce the space taken up by the two challenges, and be future proof for when someone wants a Five-Ton challenge.

The  Single-Ton badge would only need to be shown alongside the Double-Ton badge if they were achieved at separate events.

**Comment by fraz3alpha** [comment]
This is completely reasonable, and was something that was in mind to do when we next spend a bit of time on the extension.
