### ISSUE TITLE
Nearest Average parkrun event Not Yet Done

### ISSUE THREAD

**Issue by markbeech** [fraz3alpha/running-challenges#238]
It is great that we now have our Average parkrun event listed in our stats, would it be possible to also list our nearest event not yet done to our average parkrun location?

**Comment by fraz3alpha** [comment]
I'm not sure that piece of information actually adds much. 

The average parkrun stat is a bit of fun as it wends it way around the map, and knowing where you are close to is a bit of extra fun to conceptualise where that is, but I don't see what people are going to do with the information of where the closest event they haven't done is to that location - it seems a bit convoluted.

We are going to add it to the explorer map in due course - then it should be pretty clear where the un-coloured cells are near it, and people can look at what they haven't done locally if that interests them
