### ISSUE TITLE
"No place like home" badge

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#248]
Badge: a little house. Or "Home run" (badge: a baseball). Or "[Passionista](https://blog.parkrun.com/au/2017/10/24/are-you-a-parkrun-passionista/)" (badge: ? a passion fruit?!!)

Awarded after the first parkrun and retained until they run at a different parkrun event.

Implications (good or bad):
- Everyone has at least one badge once they've done their first parkrun.
- Challenge is to retain it by continuing to attend a single parkrun event (location).
- If you move house, or your local parkrun closes, and you have to parkrun elsewhere, you'd lose it.
- No one could complete *all* the running (green) badges. This would equalise the experience of non-UK parkrunners who already can't realistically complete all the challenges (eg Full Ponty).

#241

**Comment by rboyatt** [comment]
Idea for a variation: achieved by your last X parkruns (or all parkruns within X weeks etc.) **all** being at your home parkrun, i.e. tourist and you'd immediately lose it, but regained by showing dedication to your home parkrun!  

A new parkrunner would gain it on their first run and somebody who moved house/home parkrun but showed dedication to new location would also be able to achieve it.

**Comment by mike-ology** [comment]
I like the idea, but how about a variation on it where you demonstrate "home loyalty" by running X parkruns at your home turf within a calendar year. So, similar to the "obsessive" badge, but only home runs are counted towards this one. I guess another name for it could be "Home-runner".

**Comment by lauracowen** [comment]
Both those ideas are good. I'll have a think. One thing we've discussed (offline) was that if it's something you lose, it's something you can't work towards (whereas all the other challenges are things you can work towards).

**Comment by josh-justjosh** [comment]
I had this problem going round in my head this morning so I've come up with this:
![image](https://user-images.githubusercontent.com/54246291/75615742-06e61d00-5b40-11ea-817b-ee2052ee8a5f.png)

TD;LR:
- If your current streak of runs at home is longer than your last streak of away runs, you get the badge
- If your last streak of home runs is longer than your current streak of away runs, you get the badge
- If your current streak of home runs is shorter than your last streak of away runs **but** your previous streak of home runs is longer than the streak of away runs, you can keep the badge (this creates a grace period for occasional travellers)

I also made a spreadsheet to calculate it: [the file is in a dropbox folder](https://www.dropbox.com/sh/t1sv457t76pq82y/AAD3ClhosAcYRa7w7RAOgzZCa?dl=0)
