### ISSUE TITLE
Name Badge missing Map

### ISSUE THREAD

**Issue by josh-justjosh** [fraz3alpha/running-challenges#266]
The new name badge, introduced in [v1.1.0](https://github.com/fraz3alpha/running-challenges/releases/tag/v1.1.0) currently doesn't have a _Show map_ button. Should it?

**Comment by fraz3alpha** [comment]
It's not broken if that's what you mean; it's not implemented.

**Comment by JazzyJ87** [comment]
Implemented this in #325 for your consideration.

**Comment by fraz3alpha** [comment]
Had to make a new PR with @JazzyJ87 's changes + an infrastructure fix, but the code to include the map has been merged
