### ISSUE TITLE
Maybe we could get the extension working for the new Chromium-based Edge

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#268]
Apparently it should be easy to make the extension available for Edge - https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension, bbut note that we don't have a Windows machine to install it on. Edge can installed on OS X though, apparently, so maybe that could work.

## Microsoft Partner Account

You need an account in order to publish stuff.

We need to choose to be either an individual, or company , from the description below we are definitely in the individual camp from the [descriptions provided](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees)

Individual account | Company account.
-- | --
Costs approximately $19 USD (one-time registration fee; the exact amount varies depending on your country or region)Shorter account verification process | Costs approximately $99 USD (one-time registration fee; the exact amount varies depending on your country or region)Requires greater account verificationRequires that your company is recognized as such in the country or region in which it is locatedAble to submit apps with restricted functionality (as described in the Microsoft Store Policies)

Looks like it costs 12 GBP from the table.

## Edge 

You can download a version from here: https://www.microsoft.com/en-us/edge

### Installing Extensions

It looks very similar to Chrome, as you might imagine

<img width="1188" alt="Screenshot 2020-06-20 at 14 12 42" src="https://user-images.githubusercontent.com/2786011/85202705-304dd300-b300-11ea-9539-3578ce7daa22.png">

Turning developer mode on allows you to load an unpacked extension, just like Chrome, but displayed a little differently

<img width="1188" alt="Screenshot 2020-06-20 at 14 13 34" src="https://user-images.githubusercontent.com/2786011/85202725-5ffcdb00-b300-11ea-9302-ed7229e097f5.png">

I loaded a recently built version of the extension, and it appeared in the list without throwing any errors:

<img width="1262" alt="Screenshot 2020-06-20 at 14 15 19" src="https://user-images.githubusercontent.com/2786011/85202758-abaf8480-b300-11ea-86d4-93b096cfa3a2.png">

Pressing the shortcut link then worked, as did populating the list of parkruns - so it must have pulled everything down OK:

<img width="1262" alt="Screenshot 2020-06-20 at 14 15 38" src="https://user-images.githubusercontent.com/2786011/85202778-c4b83580-b300-11ea-8628-8d6a5c78f1a1.png">

And lo, there are badges!

<img width="1262" alt="Screenshot 2020-06-20 at 14 15 56" src="https://user-images.githubusercontent.com/2786011/85202785-cda90700-b300-11ea-9e28-36920d564da0.png">

Should I just pay the £12 and get it in the store?

### Extension Submission

Submitting it seemed to follow the same general process as the Mozilla and Chrome stores, asking for some images for the store, description, security policy etc...

I filled in all the forms, and now it is in review:

<img width="684" alt="Screenshot 2020-06-20 at 14 52 18" src="https://user-images.githubusercontent.com/2786011/85203450-dcde8380-b305-11ea-9e79-cc5e18d80f69.png">

**Comment by rboyatt** [comment]
That sounds good and pleased to hear it was straightforward.  I _think_ I've got a Windows VM that I can try it on...

**Comment by fraz3alpha** [comment]
Thanks for the offer @rboyatt ! I imagine it works just the same on both platforms, and given it needed no modification, I'm reasonably confident it would work on Windows - but maybe we could just put it out there and see what happens! I'm sure someone will tell us if it doesn't, and we have had one tweet about it - https://twitter.com/Kalliisborne/status/1273995222930857989

**Comment by fraz3alpha** [comment]
@rboyatt , if you want to try the extension on Edge for either OSX or Windows, you can download the latest Chrome zip from the releases tab - https://github.com/fraz3alpha/running-challenges/releases/tag/v1.1.3 , unpack it, and load it in as I did in the description above.

There were literally no changes from Chrome when I tried it in Edge for OSX, and I uploaded the same zip to the Edge extension store.

**Comment by rboyatt** [comment]
@fraz3alpha Thanks - just been trying version from git.  Unsurprisingly I guess, it all seems to work ok.  Windows 10 and Edge 83.0.478.54.

![running-challenges-newedge](https://user-images.githubusercontent.com/900659/85205161-562fa380-b311-11ea-8b03-38863f12e192.png)

**Comment by rboyatt** [comment]
P.S. Assume that did end up being only £12?  Happy to donate something if that's going to end up costing more.

**Comment by fraz3alpha** [comment]
It hasn't charged us yet, I assume it will if I want to publish it after it
passes the review....

**Comment by fraz3alpha** [comment]
This just appeared in the store: https://microsoftedge.microsoft.com/addons/detail/running-challenges/cfofipfcckojdhjbganfgflkiebajegg  - they sent us an email saying it had passed their tests after submitting it over the weekend.

I haven't paid them any money, so I don't know what's going on - but it seems to be available?!?

**Comment by rboyatt** [comment]
Yes, seems to be available!  I've managed to install from the store on a copy of Edge and it seems to be working well.
