### ISSUE TITLE
(Not)parkrun support

### ISSUE THREAD

**Issue by rboyatt** [fraz3alpha/running-challenges#269]
While normal parkrun has suspended, (not)parkrun has been introduced. 
 See https://blog.parkrun.com/uk/2020/06/10/notparkrun-is-here/ for details.

As somebody will inevitably ask anyway - should the extension support (not)parkrun?  I think this might be an easy 'no' as they don't seem to appear on individual profile pages.  Unless I've missed some info that they will do so later?

**Comment by fraz3alpha** [comment]
I don't think we know how it will appear on the website yet, so lets see what happens after Sunday when the first week comes to a close and this weeks results are collated.
