### ISSUE TITLE
Extension no longer exists in the Chrome store.

### ISSUE THREAD

**Issue by solarisfire** [fraz3alpha/running-challenges#283]
I got a message saying that the plugin was being disabled as it contained malware...

Went to check the listing on the chrome web store and it's gone...

**Comment by josh-justjosh** [comment]
Possibly (probably) related to #280.

I believe if you go to [chrome://extensions/](chrome://extensions/) you should be able to reenable the extension.

**Comment by fraz3alpha** [comment]
Thanks for linking to that other issue @josh-justjosh . I've looked at the extension developer page and it seems we also need to agree to the developer terms and conditions, answer why we need to store any data (we store the user provisioned athlete ID and home parkrun) as well as update those https links to be compliant.
I've provisionally answered the questions, but I don't think I can resubmit it for review until we've uploaded a new version

**Comment by fraz3alpha** [comment]
For everyone who comes this way looking for when it'll be fixed: it'll be fixed when we can look at it, but at the moment we have no spare time at home - see "Changes at home" on https://running-challenges.co.uk/2021/01/29/2021-update.html

**Comment by fraz3alpha** [comment]
This evening I have submitted a new version to the Chrome webstore:

![Screenshot 2021-05-16 at 20 30 59](https://user-images.githubusercontent.com/2786011/118410123-c9f34100-b685-11eb-8a1a-f24cee63d893.png)

I had to justify all the permissions it uses, and fill in the privacy information -as we don't collect any personal information I believe I was correct to leave all the privacy boxes unticked. The only personal data that is used is the parkrun ID and home parkrun which only servers to make the link and the data right, it doesn't get transmitted anywhere

PR #285 fixed all the issues that were currently a problem, so hopefully that is enough to pass the review. Unfortunately it said it could be a while before it is reviewed, but I did tick the box to automatically publish it when it does pass.

**Comment by solarisfire** [comment]
I know the vast majority of parkrunners who use the extension aren't github users, but I'd expect they'll all be overjoyed that the extension works when we get back to parkrunning.

Thank you so much!

**Comment by fraz3alpha** [comment]
Round and round we go, apparently they have added a privacy policy box in the account section, not under the extension, so we got rejected on that. I've added the link (https://running-challenges.co.uk/privacy/)  and we'll try again:

> Violation(s):
> 
> User Data Privacy:
> 
> Violation reference ID: Purple Nickel
> Violation: Privacy policy link is not available in the designated field. Note that adding the privacy policy link in your item's description is not acceptable.
> How to rectify: Add a publicly accessible link to your privacy policy in the designated field (found in the “Account” section) in your developer dashboard.
> Relevant section of the program policy:
> If your Product handles personal or sensitive user data, then your Product must post a privacy policy. (learn more)

**Comment by fraz3alpha** [comment]
I think we are back in business :) 

![Screenshot 2021-05-17 at 17 37 38](https://user-images.githubusercontent.com/2786011/118525406-0d59b800-b737-11eb-851c-f003980c1eda.png)

![Screenshot 2021-05-17 at 17 41 35](https://user-images.githubusercontent.com/2786011/118525485-2498a580-b737-11eb-894c-be8861513b51.png)

I've re-added it and it doesn't say it is disabled now on chrome://extensions/, so I don't know how it will look to end users.

@solarisfire , what does it look like from your end? Did you have to do anything in particular to get it to show?

**Comment by solarisfire** [comment]
I'd removed the extension as the "We've disabled a potentially dangerous extension" errors constantly popping up were getting annoying 😅

But I've re-added it to the browser and looks good so far.

**Comment by fraz3alpha** [comment]
Fair enough! I wonder if it will either get re-enabled, or stop getting disabled, for those who kept it.
