### ISSUE TITLE
Include date of when longest tourism streak ended

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#292]
Would be great to have the longest tourism streak to include the date of when the streak ended?

> Longest tourism streak        6 parkruns (ended 14 August 2020 at Alice Holt)

(Paul Blacknell)

**Comment by JazzyJ87** [comment]
I suggest that when a new streak equals that of the previous streak, it supersedes it; as it would be more useful to know if your latest streak is the longest. Also, if your current streak is the longest then it hasn't technically ended. Perhaps 'to' should replace 'ended'?

![image](https://user-images.githubusercontent.com/41924937/129621452-0a159b40-142b-4797-95c3-6e95cac8497b.png)

**Comment by blacknell** [comment]
I'd agreed other than the last point. It's a streak nonetheless. If I'd just bettered my previous one, it'd count in my book.

**Comment by blacknell** [comment]
Rather than 'ended' perhaps 'achieved'?

**Comment by blacknell** [comment]
Closes #294 - can someone close this issue as it's done! thanks by the way
