### ISSUE TITLE
Extension Broken with new Website Update

### ISSUE THREAD

**Issue by josh-justjosh** [fraz3alpha/running-challenges#301]
Various things have changed on the results pages, as well as a new page at https://www.parkrun.org.uk/parkrunner/**athleteID**/all/
The error being displayed is ```Error: Map container not found.```

On the plus side, it does appear that more of an athlete's result data - including (not)parkruns, freedom runs and volunteering (including a "Total Credits" row) is being displayed on the athleteeventresultshistory page

Here's the [log file](https://github.com/fraz3alpha/running-challenges/files/7296194/www.parkrun.org.uk-1633542940098.log) I got when I loaded https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=4196740&eventNumber=0

Update of details from @fraz3alpha :
## Current page structure

N.B. All links go to me - 1309364.

- Going to an event and clicking on your name gets you to: https://www.parkrun.org.uk/winchester/results/athletehistory/?athleteNumber=1309364. It has a link to our badges page as normal.
- Clicking through to "summary stats for this athlete" gets you to: https://www.parkrun.org.uk/results/athleteresultshistory/?athleteNumber=1309364. This page appears to be the same as usual, apart from the addition of the "Total Credits" line in the `Volunteer Summary` section. It has a link to our badges page as normal.
- Click through to "All" at the bottom of the event page takes you to https://www.parkrun.org.uk/parkrunner/1309364/all/. This used to be the page that our badges appeared on as it linked to https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=1309364&eventNumber=0. The addition of `eventNumber=0` appears to do nothing now, and you just get the same page as https://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=1309364.
- The badges should appear on https://www.parkrun.org.uk/parkrunner/1309364/all/, apart from that I think the other pages should continue to work as normal, and perhaps athleteeventresultshistory should gain a link to all. Some of these pages may go again in the future, but https://www.parkrun.org.uk/parkrunner/1309364/all/ seems to be the place to migrate to.

**Comment by rboyatt** [comment]
The new structure seems to have been deployed across all variants of the parkrun site (as far as I can see), and I've added another commit into the branch above that accounts for that.  

I think the combination of both changes in that branch will now fix the extension for all users.  Hope that helps and ensures you can spend a bit more time with the junior developer :)

**Comment by fraz3alpha** [comment]
If there are any more changes required, please make a PR against the branch `2021-10-website-changes` - https://github.com/fraz3alpha/running-challenges/tree/2021-10-website-changes

**Comment by fraz3alpha** [comment]
Just had to fix a couple of errors in the manifest (trailing comma, and the polyfill included in Firefox where it isn't needed - it's only for Chrome), but it's passing the checks again now

**Comment by fraz3alpha** [comment]
Here's a screenshot generated from the Austrian site:
![screenshot-main](https://user-images.githubusercontent.com/2786011/137811791-9be89e37-1b73-4cb8-9e05-dfe42cb05d67.png)

**Comment by fraz3alpha** [comment]
I think we are all good here, I'll close this - although please let me know if there is still something broken
