### ISSUE TITLE
Tutu badge

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#320]
There are usually only 2 Saturdays in a year that fall on the 22 Saturday of a month.
This month there is the first one on the 22 of January 2022 and the next one will be on the 22 of October 2022 - it could be called the tutu badge I have attached a picture. You could achieve it if you run on both of these dates ?

Gillian R

**Comment by pwhettlock** [comment]
We had two pacers at Halifax parkrun today - both wearing tutus! 

We're planning to make more a thing of it in Jul, but were celebrating our "Triple Nelson" event this morning.
