### ISSUE TITLE
Set up simple blog with GitHub Pages

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#33]
To provide:

- [x] Link to extension on Chrome web store (inc where to give feedback)
- [x] Post of what's new in each release (for anyone interested)
- [ ] 'About' - Brief background and ethos (inc criteria we use when deciding whether to include challenges)
- [x] A 'how to install and use the Chrome extension' for beginners.
- [ ] Request for translations of certain strings (list of strings and screenshots of where they appear).
- [ ] Link to GItHub issues
- [x] Link to give feedback (ie point to entry on Chrome Web Store).
- [ ] Link to parkrun for people who've stumbled on this and are not already parkrunners!
- [ ] Acknowledgements (UK parkrun tourist group, statsgeek group, parkrun!)
- [ ] Reasons for 'Other' volunteer role (see Charlie's post)

**Comment by fraz3alpha** [comment]
Marking this as closed as we've done a bunch of these tasks in our current website, which is working nicely I think - we can have separate extra issues for adding specific extra bits on
