### ISSUE TITLE
parkrun.pl stopped working - gets stuck at "parsing results"

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#361]
The issue seems to be that parkrun have changed the title of the results table from "Wszystkie rezultaty" to "Ukończone edycje parkrun", which means the extension can't find the results (there is actually an error in the browser console log if you open the developer tools panel).

**Comment by rboyatt** [comment]
I think the changes are more extensive than the name of the results table.  While preparing a patch to fix the results table, checked results pages and noticed that volunteer information wasn't appearing correctly.  I think multiple volunteer roles have been renamed.

For example: Equipment Storage and Delivery was "Przechowanie sprzętu" but now appears to be "Przechowując(a)y wyposażenie", and Pre-event Setup was "Rozstawienie oznakowań" but now appears to be "Rozstawiając(a)y oznakowanie".

**Comment by fraz3alpha** [comment]
I should have looked at the checks sooner, there was a syntax error in the i18n file - a comma inside the quotes rather than outside, I'll fix it elsewhere

**Comment by rboyatt** [comment]
Apologies, that comma was my fault I think.  Thanks for catching.

**Comment by t3d** [comment]
Unfortunately this "Parsing Results" freeze is still there (Firefox).

In the Inspector (or whatever the tool is called) I can see

> TypeError: parkruns_completed_sorted[0] is undefined content-script-parkrunner.js:211:3
>     parse_results_table moz-extension://d625bc3a-809d-47c0-a492-235374a75e92/js/content-scripts/content-script-parkrunner.js:211
>     create_page moz-extension://d625bc3a-809d-47c0-a492-235374a75e92/js/content-scripts/content-script-parkrunner.js:526
>     <anonymous> moz-extension://d625bc3a-809d-47c0-a492-235374a75e92/js/content-scripts/content-script-parkrunner.js:659
>     inject resource://gre/modules/ExtensionContent.jsm:593
>     AsyncFunctionNext self-hosted:810
>

**Comment by fraz3alpha** [comment]
@t3d , which version of the extension were you trying this with? - one of the branch builds, i presume (as the code isn't in the released version yet)?

**Comment by t3d** [comment]
Oh, sorry, I'm using the 1.3.1.257. I just assumed this was released after the fix was done.

**Comment by fraz3alpha** [comment]
That's ok! I'm on holiday this week, we might be able to upload the fixed version unless we find anything else that is broken - so it's good news you were using the last released version
