### ISSUE TITLE
Add new volunteer role "parkwalker"

### ISSUE THREAD

**Issue by pwhettlock** [fraz3alpha/running-challenges#363]
In Oct 2022, parkrun introduced the new volunteer role of "[parkwalker](https://volunteer.parkrun.com/principles/volunteer-roles)".

Athlete [ID 519096](https://www.parkrun.org.uk/parkrunner/519096/) can be used to test this, and [Halifax parkrun](https://www.parkrun.org.uk/halifax/futureroster/) has regular parkwalkers on their rota.

This will require a new vest-style badge, which I've mocked-up.

![image](https://user-images.githubusercontent.com/74610113/195987531-3502d087-ccf3-4ccb-a249-c072420dff43.png)

Maybe a good time to also refresh the RD vest to avoid confusion - not 100% sure if the bottom should now be blue or black?

![image](https://user-images.githubusercontent.com/74610113/195987580-16e76ec9-b72a-4d8e-89d3-b9538b604010.png)

**Comment by pwhettlock** [comment]
HQ have confirmed [parkwalkers are here to stay!](https://blog.parkrun.com/uk/2022/10/31/parkwalkers-are-here-to-stay/)

**Comment by pwhettlock** [comment]
I can see @sneaker-net has made a pull request for the code files: https://github.com/fraz3alpha/running-challenges/pull/364

Assuming they're OK, just need the images sorting(?)

**Comment by fraz3alpha** [comment]
https://github.com/fraz3alpha/running-challenges/pull/381 has the changes to add it, and it is available from https://github.com/fraz3alpha/running-challenges/actions/runs/4758726514


![Screenshot from 2023-04-20 21-52-39](https://user-images.githubusercontent.com/2786011/233485314-76278dec-ab76-472a-bf01-1271088139ba.png)
