### ISSUE TITLE
Technical_Event_Information wiki page deleted

### ISSUE THREAD

**Issue by rboyatt** [fraz3alpha/running-challenges#385]
https://wiki.parkrun.com/index.php/Technical_Event_Information has been deleted from the parkrun wiki.

I believe the table on this page was used to determine the 'status' of each parkrun, which is then used to filter to 'Live' events only.  Users of the extension may see the following message

> ! Unable to fetch parkrun event status data: Stats and Challenges, e.g. Regionnaire, may include events that haven't started yet !

And notice that some challenges include events that haven't started yet.

**Comment by fraz3alpha** [comment]
Oh!

**Comment by fraz3alpha** [comment]
Oh!

As I recall this was added, in part, to make the regionnaire badge be possible - as new events were constantly being added, even before they were live, so it became nearly impossible to get the badge.

Maybe that is less of a problem now, with no regionnaire, and if events on the map are really there. Perhaps the record breaker badge would have the same issue, but maybe it's fine

**Comment by pwhettlock** [comment]
Would the [Anniversaries page](https://wiki.parkrun.com/index.php/Anniversaries) be a suitable alternative?

**Comment by rboyatt** [comment]
Potentially but given the large scale wiki changes taking place, I wonder if that page will remain?

And @fraz3alpha suggested it may not be necessary anyway.

**Comment by johnsyweb** [comment]
This appears to be the reason for a bunch of anomalies, including #366. <https://wiki.parkrun.com/index.php/Technical_Event_Information> was deleted on 2023-05-02.

Perhaps more problematic is that now that all events are being considered "live", a soon-to-launch event can be displayed as a NENDY, prompting avid tourists to flock to inaugural / launch events.

**Comment by fraz3alpha** [comment]
Fixed in v1.4.0, uploaded yesterday. Seems to be available in Chrome and Firefox now
