### ISSUE TITLE
(unknown) Appearing next to each item in the Home parkrun Selector

### ISSUE THREAD

**Issue by josh-justjosh** [fraz3alpha/running-challenges#386]
In the options window `(unknown)` is being shown next to each of the parkruns

![image](https://user-images.githubusercontent.com/54246291/236792831-649b9171-04fd-404f-8e5a-b6cfd45e8bf3.png)

possibly a result of #385?

**Comment by rboyatt** [comment]
Yes, I think you're correct that it's a result of #385 - the brackets display the status of the event (in `update_home_parkrun_dropdown()` in `options.js`), which is now not being retrieved (in `get_geo_data()` in `background.js`).

**Comment by fraz3alpha** [comment]
Fixed in v1.4.0, uploaded yesterday. Seems to be available in Chrome and Firefox now
