### ISSUE TITLE
Parkrun Obsessive challenge not stacking cumulatively

### ISSUE THREAD

**Issue by anthonyclissold** [fraz3alpha/running-challenges#400]
I just ran my 50th parkrun this year, last year I ran 39. The parkrun obsessive challenge now only shows me as having completed the 30+ and 50+ levels, but not 40+.

Can the extension be modified to run this achievement cumulatively? It doesn't really make sense in its current form.

**Comment by anthonyclissold** [comment]
Likewise, the record breaker should be built in a similar way if not already

**Comment by fraz3alpha** [comment]
No, that's how it works. It's supposed to be like a medal at the Olympics - you don't get the bronze and silver ones when you also win gold.
