### ISSUE TITLE
Investigate supporting as Firefox extension too

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#54]
Privacy reasons etc, some people prefer not to use Chrome.

Additional benefit that Firefox extensions also work (with care: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Differences_between_desktop_and_Android) on Android, thus bringing it to mobile for Android users (though not for iOS because Apple doesn't permit it, I believe).

Note for anyone reading this and curious: We can't (personally) support Safari because we don't have iOS devices to test on or developer accounts/skills for iOS apps.

**Comment by fraz3alpha** [comment]
We've got the first version out, so I'll close this issue - we can open others if there are bugs and other kinks to work out
