### ISSUE TITLE
Determine country flags from URL domain suffix

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#55]
eg I have no French flag on my profile. I can only assume because Mandavit no longer exists?

Given a link still exists to the results which shows it was a .fr I would have thought it's possible for the extension to know you've been to France. https://www.facebook.com/groups/571983126241545/permalink/1458866500886532/?comment_id=1459454640827718&reply_comment_id=1460251737414675&comment_tracking=%7B%22tn%22%3A%22R9%22%7D

This would work as long as the parkrun sites don't get moved on to a single common domain. Would work for now anyway (which is the status of the extension itself...).

**Comment by fraz3alpha** [comment]
Someone who ran in Zimbabwe: http://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=8078&eventNumber=0
Someone who ran in Iceland: http://www.parkrun.org.uk/results/athleteresultshistory/?athleteNumber=70286
Someone who ran in Mandavit (defunct): http://www.parkrun.fr/results/athleteeventresultshistory/?athleteNumber=27006&eventNumber=0
