### ISSUE TITLE
Finish Token Bingo Challenge

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#6]
From UK parkrun Tourists:

Colin Naman Great work :) I also track my finish token bingo i.e.0 to 99 but being a bit of a plodder I use the last 2 digits as my finish tokens are often in 3 figures :) I am on 81/100

This should be relatively straightforward to work out and most people would be able to make good progress through regular attendance.

**Comment by ajhepple** [comment]
Don't forget also, that some parkruns attract less than 100 runners and that runners at these events may not be able to travel to busier locations. I'm thinking of events on islands or inside prisons, for example.

**Comment by DerekBlount** [comment]
Yes! Bushy, and the Three Pontys are only 9000km from my home run and 
even further to over 300 more parkruns. No problem with those challenges 
though!
