### ISSUE TITLE
Mile High Club Challenge

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#7]
A curated list of parkrun altitudes would be needed, so this would be a fixed set like 'The Full Ponty'

**Comment by DerekBlount** [comment]
Mile High parkruns : Albert's Farm, Bethlehem, Bezuidenhout, Boksburg, Delta, Dullstroom, Ebotse, Harriesmith, Ladybrand, Roodepoort, Secunda, Victoria Lake, Westbury, Witbank, (New Course? the old couse is in, but there is no accurate measurement of the new course.) and Boulder Creek.
Difficult to get a Full House now with Boulder in the mix.

**Comment by DerekBlount** [comment]
And from 7th April, Aspen in USA.

**Comment by lauracowen** [comment]
Alternatively, the highest parkrun in each country (top-level region)? To make it more accessible to all.

**Comment by DerekBlount** [comment]
Yes, good idea. Not too much difference in Denmark, probably Braband.
