### ISSUE TITLE
Home Run

### ISSUE THREAD

**Issue by DerekBlount** [fraz3alpha/running-challenges#82]
Quite a few parkrunners do not know what their Home Run is. Could the Home Run be put in with the Stats? The NENDY and Distance Travelled are based on the Home Run, so just above it? Voortrekker was closed for 18 months, but despite repeated appeals to people to change their Home Run, few actually did. I think that drawing attention to the Home Run on the Stats would serve as a reminder, that the stats are only accurate if the correct Home Run is registered.

**Comment by fraz3alpha** [comment]
Hi Derek,
The extension doesn't know what home run the runner has registered with parkrun, so we don't have that information - it isn't listed anywhere on the parkrun site that I know of, which I guess is your point, but the extension can't see any information that isn't public as it only looks at the webpages you are viewing. The home run we refer to, and use for calculations, is the one set specifically in the Running Challenges options page (alongside the athlete id), which can be anything the user chooses, and doesn't have to match the one parkrun HQ knows about.

**Comment by DerekBlount** [comment]
Hi Andy

Thanks for your response. I thought that it may be difficult. Many 
people have no idea on their home Run. It is a pity that it isn't 
readily available. I would love to see in the results where visitors are 
from, and going through the Web FMS to find out is a mission.

Great APP, long may it continue.


Kind Regards



Derek Blount
