### ISSUE TITLE
"Parkrun Range" stat

### ISSUE THREAD

**Issue by fraz3alpha** [fraz3alpha/running-challenges#87]
What are the largest and smallest parkruns attended?

e.g. The smallest parkrun you were at had 7 people @ Uditore 20150403, and the largest parkrun had 1700 @ Bushy 20180101.

As suggested by Danny Norman and Nicola Forwood on the first two episodes of the ~~"Here With Me"~~ "With Me Now" podcast in July 2018.

**Comment by fraz3alpha** [comment]
The main problem with finding this statistic out is there is no single record of the attendances of each parkrun. 

The closest, is the **event history** page for **each** parkrun, e.g. http://www.parkrun.org.uk/winchester/results/eventhistory/ . This would mean that it would take one additional web query for each distinct parkrun you have attended. i.e. if you only ever ran at Winchester, then you only need to do one more query, but if you do a different parkrun every week and have done 200 different parkruns, then 200 additional web queries are required.

The only way to avoid this being horrendous is to cache the event attendances, either locally in the extension, or perhaps externally. The first is feasible, but adds a lot of web requests, and is likely to get a temporary ban from the parkrun website (which happens if you make too many queries within a set period of time) when first fetching the data. The second is not possible currently because there is no central store of data shared between users, the extension keeps all data local and does not publish any information externally (either for tracking purposes, or for caching information centrally).

**Comment by rboyatt** [comment]
I'm not saying this is ideal but could you include a pre-cached set of event attendance data in the plugin?  So building the attendance history across all events as part of the plugin build process.  It would drift out of date but perhaps with periodic releases of the plugin it wouldn't be _too_ awful.  

Could potentially make use of the attendance records page, which has 'this week' attendance and 'record attendance' data - http://www.parkrun.org.uk/results/attendancerecords/.
