### ISSUE TITLE
Tourism Streak

### ISSUE THREAD

**Issue by JazzyJ87** [fraz3alpha/running-challenges#90]
Could you add a new stat? The greatest number of different parkruns completed consecutively, i.e. Tourism Streak.

Even got code for you:

```javascript
function generate_stat_tourism_streak(parkrun_results) {
  var t_streak = 0
  let event_streak = []

  parkrun_results.forEach(function (parkrun_event, index) {

    if (event_streak.includes(parkrun_event.name)) {

      var f = 0
      var filteredElements = event_streak.some(function(item, index) {
         f = index; return item == parkrun_event.name
      })

      event_streak.splice(0,f+1)

    }

      event_streak.push(parkrun_event.name)
      t_streak = Math.max(t_streak, event_streak.length)

  })

  return {
    "display_name": "Longest tourism streak",
    "help": "The number of different parkruns completed consecutively.",
    "value": t_streak
  }
}
```

**Comment by fraz3alpha** [comment]
This will be in the next version, v0.7.3

**Comment by fraz3alpha** [comment]
#123 doesn't work. I should have paid more attention to what the sample code provided by @JazzyJ87  was doing :) I'll have another go.

**Comment by JazzyJ87** [comment]
Sorry Andy. It was working before the last Chrome update.

**Comment by JazzyJ87** [comment]
Sorry Andy. It was working before the last Chrome update.

**Comment by JazzyJ87** [comment]
> #123 doesn't work. I should have paid more attention to what the sample code provided by @JazzyJ87 was doing :) I'll have another go.

@fraz3alpha 

I've downloaded the 7.2.160 source and added the sample code and it seems to work for me - 3486234. Is there a case you were trying where it didn't work?

**Comment by JazzyJ87** [comment]
Thanks Andy. Happy to have helped. I was making a stack. If the current queried pr is in the stack, chopping of that and anything below that before adding it back to the top again. Come to think of it, I can't remember what the some call is doing, or where filteredElements variable comes in.

**Comment by fraz3alpha** [comment]
Looks like the `.some()` call is counting the number of elements to chop off the start, and break out (by returning `true`) when it meets the duplicate parkrun event. `filteredElements` would contain an array of the elements we are about to chop off if I have read it right.

**Comment by JazzyJ87** [comment]
Ah yes. That's it. Guess I used the filteredElements for debugging.

**Comment by fraz3alpha** [comment]
OK, your algorithm is merged into master now :)

I should hopefully be able to put a new version out into the webstore this weekend - I'm going to try and get one more change in before I do so, but if it takes too long, I'll just ship what we've got :)
