### ISSUE TITLE
parkrun every date of the year

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#98]
(bit like stopwatch bingo but for each date of the year, inc 29th Feb - next Sat 29th Feb is in 2020)

Need to account for parkrun vs junior parkrun events - allow only Saturdays?

Record the year for each date achieved?
Provide 'next available Saturday' for each date that hasn't yet been achieved.

Prob requires #97 to be completed first as this will be a loooooong table of dates.

**Comment by rboyatt** [comment]
I was interested in how this worked out, so there's a first go at implementing this in the following branch: https://github.com/rboyatt/running-challenges/tree/parkrun-every-date-of-year

Agree that #97 is needed before this could go any further.  Lots and lots of scroll!

**Comment by rboyatt** [comment]
Worth noting the branch pasted above only considers Saturdays at the moment.  So it doesn't account for junior parkrun, nor does it know about parkrun not on Saturdays such as Christmas and New Year's Day.

I could add something in for those but didn't  at that point...
